# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)



# Categories
# 親要素

asia = Category.create(:name=>"アジア")
euro = Category.create(:name=>"ヨーロッパ")
africa = Category.create(:name=>"アフリカ")
northAmerica = Category.create(:name=>"北米")
southAmerica = Category.create(:name=>"中南米")
oceania = Category.create(:name=>"オセアニア")

# 子要素
asia_india = asia.children.create(:name=>"インド")
asia_indonesia = asia.children.create(:name=>"インドネシア")
asia_cambodia = asia.children.create(:name=>"カンボジア")
asia_singapore = asia.children.create(:name=>"シンガポール")
asia_srilanka = asia.children.create(:name=>"スリランカ")
asia_thailand = asia.children.create(:name=>"タイ")
asia_nepal = asia.children.create(:name=>"ネパール")
asia_pakisutan = asia.children.create(:name=>"パキスタン")
asia_banguradesh = asia.children.create(:name=>"バングラディシュ")
asia_eastthimole = asia.children.create(:name=>"東ティモール")
asia_phillipine = asia.children.create(:name=>"フィリピン")
asia_burtan = asia.children.create(:name=>"ブータン")
asia_brnei = asia.children.create(:name=>"ブルネイ")
asia_vietnam = asia.children.create(:name=>"ベトナム")
asia_malaysia = asia.children.create(:name=>"マレーシア")
asia_myanmar = asia.children.create(:name=>"ミャンマー")
asia_morudhibu = asia.children.create(:name=>"モルディブ")
asia_mongolia = asia.children.create(:name=>"モンゴル")
asia_laos = asia.children.create(:name=>"ラオス")
asia_korea = asia.children.create(:name=>"韓国")
asia_china = asia.children.create(:name=>"中国")
asia_taiwan = asia.children.create(:name=>"台湾")
asia_hongkongMacau = asia.children.create(:name=>"香港・マカオ")

euro_iceland = euro.children.create(:name=>"アイスランド")
euro_iruland = euro.children.create(:name=>"アイルランド")
euro_azerubaijan = euro.children.create(:name=>"アゼルバイジャン")
euro_arubania = euro.children.create(:name=>"アルバニア")
euro_arumenia = euro.children.create(:name=>"アルメニア")
euro_andora = euro.children.create(:name=>"アンドラ")
euro_italy = euro.children.create(:name=>"イタリア")
euro_ukrain = euro.children.create(:name=>"ウクライナ")
euro_uzbekistan = euro.children.create(:name=>"ウズベキスタン")
euro_estonia = euro.children.create(:name=>"エストニア")
euro_austolia = euro.children.create(:name=>"オーストリア")
euro_holand = euro.children.create(:name=>"オランダ")
euro_kazafstan = euro.children.create(:name=>"カザフスタン")
euro_northmakedonia = euro.children.create(:name=>"北マケドニア")
euro_kipros = euro.children.create(:name=>"キプロス")
euro_grish = euro.children.create(:name=>"ギリシャ")
euro_kirugis = euro.children.create(:name=>"キルギス")
euro_kroatia = euro.children.create(:name=>"クロアチア")
euro_kosobo = euro.children.create(:name=>"コソボ")
euro_sanmarino = euro.children.create(:name=>"サンマリノ")
euro_georgia = euro.children.create(:name=>"ジョージア")
euro_swizland = euro.children.create(:name=>"スイス")
euro_sweden = euro.children.create(:name=>"スウェーデン")
euro_spanish = euro.children.create(:name=>"スペイン")
euro_srobakia = euro.children.create(:name=>"スロバキア")
euro_srobenia = euro.children.create(:name=>"スロベニア")
euro_serbia = euro.children.create(:name=>"セルビア")
euro_tagikistan = euro.children.create(:name=>"タジキスタン")
euro_chzech = euro.children.create(:name=>"チェコ")
euro_denmark = euro.children.create(:name=>"デンマーク")
euro_douch = euro.children.create(:name=>"ドイツ")
euro_torkumenistan = euro.children.create(:name=>"トルクメニスタン")
euro_norwe = euro.children.create(:name=>"ノルウェー")
euro_batikan = euro.children.create(:name=>"バチカン")
euro_hungary = euro.children.create(:name=>"ハンガリー")
euro_finland = euro.children.create(:name=>"フィンランド")
euro_france = euro.children.create(:name=>"フランス")
euro_brugaria = euro.children.create(:name=>"ブルガリア")
euro_berarusi = euro.children.create(:name=>"ベラルーシ")
euro_bergimu = euro.children.create(:name=>"ベルギー")
euro_bosnia = euro.children.create(:name=>"ボスニア・ヘルツェゴビナ")
euro_poland = euro.children.create(:name=>"ポーランド")
euro_porutgaru = euro.children.create(:name=>"ポルトガル")
euro_marta = euro.children.create(:name=>"マルタ")
euro_monako = euro.children.create(:name=>"モナコ")
euro_morudoba = euro.children.create(:name=>"モルドバ")
euro_monteneguro = euro.children.create(:name=>"モンテネグロ")
euro_latvia = euro.children.create(:name=>"ラトビア")
euro_ritania = euro.children.create(:name=>"リトアニア")
euro_rihitenshtain = euro.children.create(:name=>"リヒテンシュタイン")
euro_ruksenburk = euro.children.create(:name=>"ルクセンブルク")
euro_romania = euro.children.create(:name=>"ルーマニア")
euro_rossia = euro.children.create(:name=>"ロシア")

africa_arje = africa.children.create(:name=>"アルジェリア")
africa_angora = africa.children.create(:name=>"アンゴラ")
africa_uganda = africa.children.create(:name=>"ウガンダ")
africa_egypt = africa.children.create(:name=>"エジプト")
africa_eswatini = africa.children.create(:name=>"エスワティニ")
africa_etiopia = africa.children.create(:name=>"エチオピア")
africa_eritoria = africa.children.create(:name=>"エリトリア")
africa_gana = africa.children.create(:name=>"ガーナ")
africa_karboverude = africa.children.create(:name=>"カーボヴェルデ")
africa_gabon = africa.children.create(:name=>"ガボン")
africa_kamern = africa.children.create(:name=>"カメルーン")
africa_ganbia = africa.children.create(:name=>"ガンビア")
africa_ginia = africa.children.create(:name=>"ギニア")
africa_giniapisau = africa.children.create(:name=>"ギニアビサウ")
africa_kenia = africa.children.create(:name=>"ケニア")
africa_kortzibowaru = africa.children.create(:name=>"コートジボワール")
africa_komoro = africa.children.create(:name=>"コモロ")
africa_kongo = africa.children.create(:name=>"コンゴ")
africa_santome = africa.children.create(:name=>"サントメ・プリンシペ")
africa_zambia = africa.children.create(:name=>"ザンビア")
africa_syerareone = africa.children.create(:name=>"シエラレオネ")
africa_zibuti = africa.children.create(:name=>"ジブチ")
africa_zinbabue = africa.children.create(:name=>"ジンバブエ")
africa_surdan = africa.children.create(:name=>"スーダン")
africa_ginia = africa.children.create(:name=>"赤道ギニア")
africa_sesyeru = africa.children.create(:name=>"セーシェル")
africa_senegaru = africa.children.create(:name=>"セネガル")
africa_somaria = africa.children.create(:name=>"ソマリア")
africa_tanzania = africa.children.create(:name=>"タンザニア")
africa_chado = africa.children.create(:name=>"チャド")
africa_middleAfrica = africa.children.create(:name=>"中央アフフカ")
africa_chunizia = africa.children.create(:name=>"チュニジア")
africa_tohgo = africa.children.create(:name=>"トーゴ")
africa_naije = africa.children.create(:name=>"ナイジェリア")
africa_namibia = africa.children.create(:name=>"ナミビア")
africa_nijeru = africa.children.create(:name=>"ニジェール")
africa_burukinafaso = africa.children.create(:name=>"ブルキナファソ")
africa_burunzi = africa.children.create(:name=>"ブルンジ")
africa_benan = africa.children.create(:name=>"ベナン")
africa_botuwana = africa.children.create(:name=>"ボツワナ")
africa_madagasukaru = africa.children.create(:name=>"マダガスカル")
africa_maraui = africa.children.create(:name=>"マラウイ")
africa_mari = africa.children.create(:name=>"マリ")
africa_southAfrica = africa.children.create(:name=>"南アフリカ")
africa_southSurdan = africa.children.create(:name=>"南スーダン")
africa_mozanbiku = africa.children.create(:name=>"モザンビーク")
africa_morishasu = africa.children.create(:name=>"モーリシャス")
africa_molitania = africa.children.create(:name=>"モーリタニア")
africa_morocco = africa.children.create(:name=>"モロッコ")
africa_libia = africa.children.create(:name=>"リビア")
africa_liberia = africa.children.create(:name=>"リベリア")
africa_rwanda = africa.children.create(:name=>"ルワンダ")
africa_resot = africa.children.create(:name=>"レソト")

northAmerica_us = northAmerica.children.create(:name=>"アメリカ")
northAmerica_canada = northAmerica.children.create(:name=>"カナダ")

southAmerica_aruzentin = southAmerica.children.create(:name=>"アルゼンチン")
southAmerica_antigua = southAmerica.children.create(:name=>"アンティグア・バーブーダ")
southAmerica_urguai = southAmerica.children.create(:name=>"ウルグアイ")
southAmerica_ekuadoru = southAmerica.children.create(:name=>"エクアドル")
southAmerica_erusarubadoru = southAmerica.children.create(:name=>"エルサルバドル")
southAmerica_gaiana = southAmerica.children.create(:name=>"ガイアナ")
southAmerica_cuba = southAmerica.children.create(:name=>"キューバ")
southAmerica_guatemara = southAmerica.children.create(:name=>"グアテマラ")
southAmerica_gurenada = southAmerica.children.create(:name=>"グレナダ")
southAmerica_costarika = southAmerica.children.create(:name=>"コスタリカ")
southAmerica_clombia = southAmerica.children.create(:name=>"コロンビア")
southAmerica_jamaika = southAmerica.children.create(:name=>"ジャマイカ")
southAmerica_surinam = southAmerica.children.create(:name=>"スリナム")
southAmerica_nevis = southAmerica.children.create(:name=>"セントクリストファー・ネーヴィス")
southAmerica_sentvinsent = southAmerica.children.create(:name=>"セントビンセント及びグレナディーン諸島")
southAmerica_centrusia = southAmerica.children.create(:name=>"セントルシア")
southAmerica_chili = southAmerica.children.create(:name=>"チリ")
southAmerica_dominikaRe = southAmerica.children.create(:name=>"ドミニカ共和国")
southAmerica_torini = southAmerica.children.create(:name=>"トリニダード・トバゴ")
southAmerica_nikara = southAmerica.children.create(:name=>"ニカラグア")
southAmerica_haiti = southAmerica.children.create(:name=>"ハイチ")
southAmerica_panama = southAmerica.children.create(:name=>"パナマ")
southAmerica_bahama = southAmerica.children.create(:name=>"バハマ")
southAmerica_paraguai = southAmerica.children.create(:name=>"パラグアイ")
southAmerica_barubados = southAmerica.children.create(:name=>"バルバドス")
southAmerica_brazil = southAmerica.children.create(:name=>"ブラジル")
southAmerica_venezuera = southAmerica.children.create(:name=>"ベネズエラ")
southAmerica_beliz = southAmerica.children.create(:name=>"ベリーズ")
southAmerica_peru = southAmerica.children.create(:name=>"ペルー")
southAmerica_boribia = southAmerica.children.create(:name=>"ボリビア")
southAmerica_honjuras = southAmerica.children.create(:name=>"ホンジュラス")
southAmerica_mexico = southAmerica.children.create(:name=>"メキシコ")

oceania_australia = oceania.children.create(:name=>"オーストラリア")
oceania_kiribas = oceania.children.create(:name=>"キリバス")
oceania_kukku = oceania.children.create(:name=>"クック諸島")
oceania_samoa = oceania.children.create(:name=>"サモア")
oceania_solomon = oceania.children.create(:name=>"ソロモン")
oceania_tubaru = oceania.children.create(:name=>"ツバル")
oceania_tomga = oceania.children.create(:name=>"トンガ")
oceania_nauru = oceania.children.create(:name=>"ナウル")
oceania_niue = oceania.children.create(:name=>"ニウエ")
oceania_newzealand = oceania.children.create(:name=>"ニュージーランド")
oceania_banuatu = oceania.children.create(:name=>"バヌアツ")
oceania_papuanewginia = oceania.children.create(:name=>"パプアニューギニア")
oceania_parao = oceania.children.create(:name=>"パラオ")
oceania_fiji = oceania.children.create(:name=>"フィジー")
oceania_marsharu = oceania.children.create(:name=>"マーシャル諸島")
oceania_mikuronesia = oceania.children.create(:name=>"ミクロネシア")



# 孫要素

asia_india.children.create([{:name=>"デリー"}, {:name=>"ムンバイ"}, {:name=>"コルカタ"}, {:name=>"チェンナイ"}, {:name=>"バンガロール"}, {:name=>"バラナシ"}, {:name=>"ハイデラバード"}, {:name=>"アグラ"}, {:name=>"ゴア"}, {:name=>"その他"}])
asia_indonesia.children.create([{:name=>"ジャカルタ"}, {:name=>"スラバヤ"}, {:name=>"メダン"}, {:name=>"デンパサール"}, {:name=>"ジョグジャカルタ"}, {:name=>"マナド"}, {:name=>"その他"}])
asia_cambodia.children.create([{:name=>"プノンペン"}, {:name=>"シェムリアップ"}, {:name=>"シアヌークビル"}, {:name=>"タクマウ"}, {:name=>"その他"}])
asia_singapore.children.create([{:name=>"オーチャード"}, {:name=>"マリーナ"}, {:name=>"チャイナタウン"}, {:name=>"ブギス"}, {:name=>"リトルインディア"}, {:name=>"カトン"}, {:name=>"その他"}])
asia_srilanka.children.create([{:name=>"コロンボ"}, {:name=>"デヒワラ"}, {:name=>"モラトゥワ"}, {:name=>"その他"}])
asia_thailand.children.create([{:name=>"バンコク"}, {:name=>"パタヤ"}, {:name=>"アユタヤ"}, {:name=>"チェンマイ"}, {:name=>"プーケット"}, {:name=>"イサーン"}, {:name=>"カンチャナブリ"}, {:name=>"その他"}])
asia_nepal.children.create([{:name=>"カトマンズ"}, {:name=>"ポカラ"}, {:name=>"ラリトプル"}, {:name=>"その他"}])
asia_pakisutan.children.create([{:name=>"イスラマバード"}, {:name=>"カラチ"}, {:name=>"ラーホール"}, {:name=>"ファイサラバード"}, {:name=>"フンザ"}, {:name=>"その他"}])
asia_banguradesh.children.create([{:name=>"ダッカ"}, {:name=>"チッタゴン"}, {:name=>"クルナ"}, {:name=>"ナラヤンガンジ"}, {:name=>"その他"}])
asia_eastthimole.children.create([{:name=>"バウカウ"}, {:name=>"ダレ"}, {:name=>"ディリ"}, {:name=>"エルメラ"}, {:name=>"その他"}])
asia_phillipine.children.create([{:name=>"マニラ"}, {:name=>"セブ"}, {:name=>"ボラカイ"}, {:name=>"ダバオ"}, {:name=>"イロイロ"}, {:name=>"タガイタイ"}, {:name=>"その他"}])
asia_burtan.children.create([{:name=>"ティンプー"}, {:name=>"プンツォリン"}, {:name=>"プナカ"}, {:name=>"サムドゥプ"}, {:name=>"その他"}])
asia_brnei.children.create([{:name=>"バンダルスリブガワン"}, {:name=>"その他"}])
asia_vietnam.children.create([{:name=>"ホーチミン"}, {:name=>"ハノイ"}, {:name=>"ダナン"}, {:name=>"フエ"}, {:name=>"ニャチャン"}, {:name=>"ホイアン"}, {:name=>"その他"}])
asia_malaysia.children.create([{:name=>"クアラルンプール"}, {:name=>"ジョホールバル"}, {:name=>"コタキナバル"}, {:name=>"ペナン"}, {:name=>"マラッカ"}, {:name=>"その他"}])
asia_myanmar.children.create([{:name=>"ヤンゴン"}, {:name=>"マンダレー"}, {:name=>"ネピドー"}, {:name=>"ベイ"}, {:name=>"タウンジー"}, {:name=>"その他"}])
asia_morudhibu.children.create([{:name=>"マレ"}, {:name=>"その他"}])
asia_mongolia.children.create([{:name=>"ウランバートル"}, {:name=>"エルデネト"}, {:name=>"ダルハン"}, {:name=>"その他"}])
asia_laos.children.create([{:name=>"ヴィエンチャン"}, {:name=>"ルアンパバーン"}, {:name=>"パークセー"}, {:name=>"その他"}])
asia_korea.children.create([{:name=>"ソウル"}, {:name=>"プサン"}, {:name=>"チェジュ"}, {:name=>"パンムンジョム"}, {:name=>"チョンジュ"}, {:name=>"その他"}])
asia_china.children.create([{:name=>"北京"}, {:name=>"上海"}, {:name=>"広州"}, {:name=>"深圳"}, {:name=>"杭州"}, {:name=>"南京"}, {:name=>"成都"}, {:name=>"武漢"}, {:name=>"西安"}, {:name=>"重慶"}, {:name=>"瀋陽"}, {:name=>"天津"}, {:name=>"厦門"}, {:name=>"青島"}, {:name=>"その他"}])
asia_taiwan.children.create([{:name=>"台北"}, {:name=>"高雄"}, {:name=>"台中"}, {:name=>"基隆"}, {:name=>"その他"}])
asia_hongkongMacau.children.create([{:name=>"尖沙咀"}, {:name=>"中環"}, {:name=>"金鐘"}, {:name=>"灣仔"}, {:name=>"銅鑼灣"}, {:name=>"上環"}, {:name=>"佐敦"}, {:name=>"油麻地"}, {:name=>"旺角"}, {:name=>"太子"}, {:name=>"天后"}, {:name=>"マカオ"}, {:name=>"その他"}])

euro_iceland.children.create([{:name=>"レイキャビーク"}, {:name=>"アークレイ"}, {:name=>"グリンダヴィーク"}, {:name=>"その他"}])
euro_iruland.children.create([{:name=>"ダブリン"}, {:name=>"コーク"}, {:name=>"ゴールウェイ"}, {:name=>"その他"}])
euro_azerubaijan.children.create([{:name=>"バクー"}, {:name=>"ギャンジャ"}, {:name=>"スムガイト"}, {:name=>"その他"}])
euro_arubania.children.create([{:name=>"ティラナ"}, {:name=>"ドゥラス"}, {:name=>"ヴロラ"}, {:name=>"その他"}])
euro_arumenia.children.create([{:name=>"エレバン"}, {:name=>"ギュムリ"}, {:name=>"ヴァナゾル"}, {:name=>"その他"}])
euro_andora.children.create([{:name=>"アンドラ・ラ・べリャ"}, {:name=>"その他"}])
euro_italy.children.create([{:name=>"ローマ"}, {:name=>"ミラノ"}, {:name=>"ナポリ"}, {:name=>"トリノ"}, {:name=>"パレルモ"}, {:name=>"ジェノヴァ"}, {:name=>"フィレンツェ"}, {:name=>"その他"}])
euro_ukrain.children.create([{:name=>"キエフ"}, {:name=>"ハルキウ"}, {:name=>"オデッサ"}, {:name=>"その他"}])
euro_uzbekistan.children.create([{:name=>"タシュケント"}, {:name=>"ナマンガン"}, {:name=>"その他"}])
euro_estonia.children.create([{:name=>"タリン"}, {:name=>"タルトゥ"}, {:name=>"ナルヴァ"}, {:name=>"その他"}])
euro_austolia.children.create([{:name=>"ウィーン"}, {:name=>"グラーツ"}, {:name=>"リンツ"}, {:name=>"その他"}])
euro_holand.children.create([{:name=>"アムステルダム"}, {:name=>"ロッテルダム"}, {:name=>"フローニンゲン"}, {:name=>"その他"}])
euro_kazafstan.children.create([{:name=>"アルマトイ"}, {:name=>"ヌルスルタン"}, {:name=>"シムケント"}, {:name=>"その他"}])
euro_northmakedonia.children.create([{:name=>"スコピエ"}, {:name=>"クマノヴォ"}, {:name=>"その他"}])
euro_kipros.children.create([{:name=>"ニコシア"}, {:name=>"リマソール"}, {:name=>"ラルナカ"}, {:name=>"その他"}])
euro_grish.children.create([{:name=>"アテネ"}, {:name=>"テッサロニキ"}, {:name=>"ピレウス"}, {:name=>"その他"}])
euro_kirugis.children.create([{:name=>"ビシュケク"}, {:name=>"オシ"}, {:name=>"ジャララバード"}, {:name=>"その他"}])
euro_kroatia.children.create([{:name=>"ザグレブ"}, {:name=>"スプリト"}, {:name=>"リエカ"}, {:name=>"その他"}])
euro_kosobo.children.create([{:name=>"プリシュティナ"}, {:name=>"プリズレン"}, {:name=>"フェリザイ"}, {:name=>"その他"}])
euro_sanmarino.children.create([{:name=>"サンマリノ"}, {:name=>"その他"}])
euro_georgia.children.create([{:name=>"トビリシ"}, {:name=>"バトゥミ"}, {:name=>"クタイシ"}, {:name=>"その他"}])
euro_swizland.children.create([{:name=>"チューリッヒ"}, {:name=>"ジュネーブ"}, {:name=>"バーゼル"}, {:name=>"ベルン"}, {:name=>"その他"}])
euro_sweden.children.create([{:name=>"ストックホルム"}, {:name=>"ヨーテボリ"}, {:name=>"マルメ"}, {:name=>"その他"}])
euro_spanish.children.create([{:name=>"マドリード"}, {:name=>"バルセロナ"}, {:name=>"バレンシア"}, {:name=>"セビリア"}, {:name=>"その他"}])
euro_srobakia.children.create([{:name=>"ブラチスラバ"}, {:name=>"トレンチーン"}, {:name=>"レボチャ"}, {:name=>"その他"}])
euro_srobenia.children.create([{:name=>"リュブリャナ"}, {:name=>"マリボル"}, {:name=>"その他"}])
euro_serbia.children.create([{:name=>"ベオグラード"}, {:name=>"ノヴィ・サド"}, {:name=>"その他"}])
euro_tagikistan.children.create([{:name=>"ドゥシャンベ"}, {:name=>"ホジェンド"}, {:name=>"その他"}])
euro_chzech.children.create([{:name=>"プラハ"}, {:name=>"ブルノ"}, {:name=>"オストラバス"}, {:name=>"その他"}])
euro_denmark.children.create([{:name=>"コペンハーゲン"}, {:name=>"オーフス"}, {:name=>"オーデンサ"}, {:name=>"その他"}])
euro_douch.children.create([{:name=>"ベルリン"}, {:name=>"ハンブルク"}, {:name=>"ミュンヘン"}, {:name=>"ケルン"}, {:name=>"フランクフルト"}, {:name=>"その他"}])
euro_torkumenistan.children.create([{:name=>"アシガーバート"}, {:name=>"テュルクメナバート"}, {:name=>"その他"}])
euro_norwe.children.create([{:name=>"オスロ"}, {:name=>"ベルゲン"}, {:name=>"トロンハイム"}, {:name=>"その他"}])
euro_batikan.children.create([{:name=>"バチカン"}, {:name=>"その他"}])
euro_hungary.children.create([{:name=>"ブダペスト"}, {:name=>"デブレツェン"}, {:name=>"ミシュコルツ"}, {:name=>"トカイ"}, {:name=>"その他"}])
euro_finland.children.create([{:name=>"ヘルシンキ"}, {:name=>"エスポー"}, {:name=>"タンペレ"}, {:name=>"その他"}])
euro_france.children.create([{:name=>"パリ"}, {:name=>"マルセイユ"}, {:name=>"リヨン"}, {:name=>"その他"}])
euro_brugaria.children.create([{:name=>"ソフィア"}, {:name=>"プロヴディフ"}, {:name=>"ヴァルナ"}, {:name=>"その他"}])
euro_berarusi.children.create([{:name=>"ミンスク"}, {:name=>"ホメリ"}, {:name=>"マヒリョン"}, {:name=>"その他"}])
euro_bergimu.children.create([{:name=>"ブリュッセル"}, {:name=>"ヘント"}, {:name=>"ブルージュ"}, {:name=>"アントワープ"}, {:name=>"その他"}])
euro_bosnia.children.create([{:name=>"サラエボ"}, {:name=>"バルニャカ"}, {:name=>"その他"}])
euro_poland.children.create([{:name=>"ワルシャワ"}, {:name=>"クラクフ"}, {:name=>"ウッチ"}, {:name=>"その他"}])
euro_porutgaru.children.create([{:name=>"リスボン"}, {:name=>"ポルト"}, {:name=>"その他"}])
euro_marta.children.create([{:name=>"マルタ"}, {:name=>"その他"}])
euro_monako.children.create([{:name=>"モナコ"}, {:name=>"その他"}])
euro_morudoba.children.create([{:name=>"キシナウ"}, {:name=>"ティラスポリ"}, {:name=>"その他"}])
euro_monteneguro.children.create([{:name=>"ポトゴリツァ"}, {:name=>"ニクシッチ"}, {:name=>"その他"}])
euro_latvia.children.create([{:name=>"リガ"}, {:name=>"その他"}])
euro_ritania.children.create([{:name=>"ヴィルニス"}, {:name=>"その他"}])
euro_rihitenshtain.children.create([{:name=>"ファドゥーツ"}, {:name=>"その他"}])
euro_ruksenburk.children.create([{:name=>"ルクセンブルク"}, {:name=>"その他"}])
euro_romania.children.create([{:name=>"ブカレスト"}, {:name=>"ヤシ"}, {:name=>"その他"}])
euro_rossia.children.create([{:name=>"モスクワ"}, {:name=>"サンクトペテルブルク"}, {:name=>"ノヴォシビルスク"}, {:name=>"エカチェリンブルック"}, {:name=>"その他"}])

africa_arje.children.create([{:name=>"アルジェ"}, {:name=>"オラン"}, {:name=>"その他"}])
africa_angora.children.create([{:name=>"ルアンダ"}, {:name=>"ウアンボ"}, {:name=>"その他"}])
africa_uganda.children.create([{:name=>"カンパラ"}, {:name=>"ナンサナ"}, {:name=>"その他"}])
africa_egypt.children.create([{:name=>"カイロ"}, {:name=>"アレクサンドリア"}, {:name=>"ギザ"}, {:name=>"その他"}])
africa_eswatini.children.create([{:name=>"マンジニ"}, {:name=>"ムババーネ"}, {:name=>"その他"}])
africa_etiopia.children.create([{:name=>"アディスアベバ"}, {:name=>"アダマ"}, {:name=>"その他"}])
africa_eritoria.children.create([{:name=>"アスマラ"}, {:name=>"ケレン"}, {:name=>"その他"}])
africa_gana.children.create([{:name=>"アクラ"}, {:name=>"クマシ"}, {:name=>"その他"}])
africa_karboverude.children.create([{:name=>"プライア"}, {:name=>"その他"}])
africa_gabon.children.create([{:name=>"リーブルヴィル"}, {:name=>"ポールジャンティ"}, {:name=>"その他"}])
africa_kamern.children.create([{:name=>"ドゥアラ"}, {:name=>"ヤウンデ"}, {:name=>"その他"}])
africa_ganbia.children.create([{:name=>"バンジュール"}, {:name=>"その他"}])
africa_ginia.children.create([{:name=>"コナクリ"}, {:name=>"その他"}])
africa_giniapisau.children.create([{:name=>"ビサウ"}, {:name=>"その他"}])
africa_kenia.children.create([{:name=>"ナイロビ"}, {:name=>"キスム"}, {:name=>"その他"}])
africa_kortzibowaru.children.create([{:name=>"アビジャン"}, {:name=>"その他"}])
africa_komoro.children.create([{:name=>"モロニ"}, {:name=>"その他"}])
africa_kongo.children.create([{:name=>"キンシャサ"}, {:name=>"ルブンバシ"}, {:name=>"ムブジマイ"}, {:name=>"その他"}])
africa_santome.children.create([{:name=>"サントメ"}, {:name=>"その他"}])
africa_zambia.children.create([{:name=>"ルサカ"}, {:name=>"その他"}])
africa_syerareone.children.create([{:name=>"フリータウン"}, {:name=>"その他"}])
africa_zibuti.children.create([{:name=>"ジブチ"}, {:name=>"その他"}])
africa_zinbabue.children.create([{:name=>"ハラレ"}, {:name=>"ブラワヨ"}, {:name=>"その他"}])
africa_surdan.children.create([{:name=>"ハルツーム"}, {:name=>"その他"}])
africa_ginia.children.create([{:name=>"コナクリ"}, {:name=>"その他"}])
africa_sesyeru.children.create([{:name=>"ヴィクトリア"}, {:name=>"その他"}])
africa_senegaru.children.create([{:name=>"ダカール"}, {:name=>"リュフィスク"}, {:name=>"その他"}])
africa_somaria.children.create([{:name=>"モガディシュ"}, {:name=>"その他"}])
africa_tanzania.children.create([{:name=>"ダルエスサラーム"}, {:name=>"ドドマ"}, {:name=>"その他"}])
africa_chado.children.create([{:name=>"ンジャメナ"}, {:name=>"サール"}, {:name=>"その他"}])
africa_middleAfrica.children.create([{:name=>"バンギ"}, {:name=>"ビンボ"}, {:name=>"その他"}])
africa_chunizia.children.create([{:name=>"チュニス"}, {:name=>"スファックス"}, {:name=>"その他"}])
africa_tohgo.children.create([{:name=>"ロメ"}, {:name=>"その他"}])
africa_naije.children.create([{:name=>"ラゴス"}, {:name=>"イバダン"}, {:name=>"その他"}])
africa_namibia.children.create([{:name=>"ウィントフック"}, {:name=>"その他"}])
africa_nijeru.children.create([{:name=>"ニアメ"}, {:name=>"ザンデール"}, {:name=>"その他"}])
africa_burukinafaso.children.create([{:name=>"ワガドゥグー"}, {:name=>"ボボ・ディウラッソ"}, {:name=>"その他"}])
africa_burunzi.children.create([{:name=>"ブジュンブラ"}, {:name=>"その他"}])
africa_benan.children.create([{:name=>"コトヌー"}, {:name=>"その他"}])
africa_botuwana.children.create([{:name=>"ハボローネ"}, {:name=>"その他"}])
africa_madagasukaru.children.create([{:name=>"アンタナナリボ"}, {:name=>"その他"}])
africa_maraui.children.create([{:name=>"リロングウェ"}, {:name=>"ブランタイヤ"}, {:name=>"その他"}])
africa_mari.children.create([{:name=>"バマコ"}, {:name=>"シカソ"}, {:name=>"その他"}])
africa_southAfrica.children.create([{:name=>"ヨハネスブルグ"}, {:name=>"ケープタウン"}, {:name=>"その他"}])
africa_southSurdan.children.create([{:name=>"ジュバ"}, {:name=>"イェイ"}, {:name=>"その他"}])
africa_mozanbiku.children.create([{:name=>"マプト"}, {:name=>"ナンプーラ"}, {:name=>"その他"}])
africa_morishasu.children.create([{:name=>"ポートルイス"}, {:name=>"その他"}])
africa_molitania.children.create([{:name=>"ヌアクショット"}, {:name=>"その他"}])
africa_morocco.children.create([{:name=>"カサブランカ"}, {:name=>"マラケシュ"}, {:name=>"フェズ"}, {:name=>"タンジェ"}, {:name=>"その他"}])
africa_libia.children.create([{:name=>"トリポリ"}, {:name=>"ベンガジ"}, {:name=>"その他"}])
africa_liberia.children.create([{:name=>"モンロビア"}, {:name=>"その他"}])
africa_rwanda.children.create([{:name=>"キガリ"}, {:name=>"ブタレ"}, {:name=>"その他"}])
africa_resot.children.create([{:name=>"マセル"}, {:name=>"その他"}])

northAmerica_us.children.create([{:name=>"ニューヨーク"}, {:name=>"ロサンゼルス"}, {:name=>"シカゴ"}, {:name=>"ヒューストン"}, {:name=>"サンアントニオ"}, {:name=>"テキサス"}, {:name=>"サンフランシスコ"}, {:name=>"マイアミ"}, {:name=>"その他"}])
northAmerica_canada.children.create([{:name=>"トロント"}, {:name=>"モントリール"}, {:name=>"バンクーバー"}, {:name=>"その他"}])

southAmerica_aruzentin.children.create([{:name=>"ブエノス・アイレス"}, {:name=>"コルトバ"}, {:name=>"ロサリオ"}, {:name=>"メンドーサ"}, {:name=>"その他"}])
southAmerica_antigua.children.create([{:name=>"セントジョンズ"}, {:name=>"その他"}])
southAmerica_urguai.children.create([{:name=>"モンテビデオ"}, {:name=>"サルト"}, {:name=>"その他"}])
southAmerica_ekuadoru.children.create([{:name=>"グアヤキル"}, {:name=>"キト"}, {:name=>"クエンカ"}, {:name=>"その他"}])
southAmerica_erusarubadoru.children.create([{:name=>"ソヤパンゴ"}, {:name=>"サンサルバドル"}, {:name=>"その他"}])
southAmerica_gaiana.children.create([{:name=>"ジョージタウン"}, {:name=>"その他"}])
southAmerica_cuba.children.create([{:name=>"ハバナ"}, {:name=>"サンティアーゴ・デ・クーバ"}, {:name=>"カマグエイ"}, {:name=>"その他"}])
southAmerica_guatemara.children.create([{:name=>"グアテマラ"}, {:name=>"ビジャ・ヌエバ"}, {:name=>"その他"}])
southAmerica_gurenada.children.create([{:name=>"セントジョーンズ"}, {:name=>"その他"}])
southAmerica_costarika.children.create([{:name=>"サンホセ"}, {:name=>"エレディア"}, {:name=>"その他"}])
southAmerica_clombia.children.create([{:name=>"ボゴタ"}, {:name=>"メテジン"}, {:name=>"カリ"}, {:name=>"その他"}])
southAmerica_jamaika.children.create([{:name=>"キングストン"}, {:name=>"ポートモア"}, {:name=>"その他"}])
southAmerica_surinam.children.create([{:name=>"パラマリボ"}, {:name=>"その他"}])
southAmerica_nevis.children.create([{:name=>"バセテール"}, {:name=>"その他"}])
southAmerica_sentvinsent.children.create([{:name=>"キングスタウン"}, {:name=>"その他"}])
southAmerica_centrusia.children.create([{:name=>"カストリーズ"}, {:name=>"その他"}])
southAmerica_chili.children.create([{:name=>"サンティアゴ"}, {:name=>"バルパライソ"}, {:name=>"その他"}])
southAmerica_dominikaRe.children.create([{:name=>"サントドミンゴ"}, {:name=>"その他"}])
southAmerica_torini.children.create([{:name=>"チャグアナス"}, {:name=>"サンフェルナンド"}, {:name=>"その他"}])
southAmerica_nikara.children.create([{:name=>"マナグア"}, {:name=>"レオン"}, {:name=>"その他"}])
southAmerica_haiti.children.create([{:name=>"ポルトーフランス"}, {:name=>"カルフール"}, {:name=>"その他"}])
southAmerica_panama.children.create([{:name=>"パナマ"}, {:name=>"サンミゲリート"}, {:name=>"その他"}])
southAmerica_bahama.children.create([{:name=>"ナッソー"}, {:name=>"その他"}])
southAmerica_paraguai.children.create([{:name=>"アスンシオン"}, {:name=>"シウダーデルエステ"}, {:name=>"その他"}])
southAmerica_barubados.children.create([{:name=>"ブリッジタウン"}, {:name=>"その他"}])
southAmerica_brazil.children.create([{:name=>"サンパウロ"}, {:name=>"リオデジャネイロ"}, {:name=>"ブラジリア"}, {:name=>"サルヴァドール"}, {:name=>"フォルタレザ"}, {:name=>"その他"}])
southAmerica_venezuera.children.create([{:name=>"マラカイボ"}, {:name=>"カラカス"}, {:name=>"その他"}])
southAmerica_beliz.children.create([{:name=>"ベリーズ"}, {:name=>"その他"}])
southAmerica_peru.children.create([{:name=>"リマ"}, {:name=>"アレキパ"}, {:name=>"トルヒーリョ"}, {:name=>"その他"}])
southAmerica_boribia.children.create([{:name=>"サンタクルス"}, {:name=>"エルアルト"}, {:name=>"ラパス"}, {:name=>"その他"}])
southAmerica_honjuras.children.create([{:name=>"テグシガルパ"}, {:name=>"サンペドロスーラ"}, {:name=>"その他"}])
southAmerica_mexico.children.create([{:name=>"メキシコシティ"}, {:name=>"カンクン"}, {:name=>"エカテペック"}, {:name=>"その他"}])

oceania_australia.children.create([{:name=>"シドニー"}, {:name=>"メルボルン"}, {:name=>"ブリスベン"}, {:name=>"アデレード"}, {:name=>"パース"}, {:name=>"その他"}])
oceania_kiribas.children.create([{:name=>"タラワ"}, {:name=>"その他"}])
oceania_kukku.children.create([{:name=>"アバルア"}, {:name=>"その他"}])
oceania_samoa.children.create([{:name=>"アピア"}, {:name=>"その他"}])
oceania_solomon.children.create([{:name=>"ホニアラ"}, {:name=>"その他"}])
oceania_tubaru.children.create([{:name=>"フナフティ"}, {:name=>"その他"}])
oceania_tomga.children.create([{:name=>"ヌクアロファ"}, {:name=>"その他"}])
oceania_nauru.children.create([{:name=>"ナウル"}, {:name=>"その他"}])
oceania_niue.children.create([{:name=>"アロフィ"}, {:name=>"その他"}])
oceania_newzealand.children.create([{:name=>"オークランド"}, {:name=>"クライストチャーチ"}, {:name=>"ウェリントン"}, {:name=>"その他"}])
oceania_banuatu.children.create([{:name=>"ポートビラ"}, {:name=>"その他"}])
oceania_papuanewginia.children.create([{:name=>"ポートモレスビー"}, {:name=>"ラエ"}, {:name=>"その他"}])
oceania_parao.children.create([{:name=>"コロール"}, {:name=>"マルキョク"}, {:name=>"その他"}])
oceania_fiji.children.create([{:name=>"スバ"}, {:name=>"その他"}])
oceania_marsharu.children.create([{:name=>"マジュロ"}, {:name=>"その他"}])
oceania_mikuronesia.children.create([{:name=>"パリキール"}, {:name=>"その他"}])

require 'faker'

# ユーザー
User.create!(
  nickname: "出品者テストユーザー",
  birth_date: Faker::Date.in_date_period,
  email: "test1@gmail.com",
  password: "123456",
  password_confirmation:"123456"
)
User.create!(
  nickname: "購入者テストユーザー",
  birth_date: Faker::Date.in_date_period,
  email: "test2@gmail.com",
  password: "123456",
  password_confirmation:"123456"
)

# 投稿

# 20.times do
#      Post.create(
#         title: Faker::DragonBall.character,
#         header_image: Faker::Avatar.image,
#         user_id:"1",
#         category_id:"1",
#         content:"美味しいよ"
#       )
# end